version: "3"

services:
  webapp:
    image: henryspeaker/car-listing-server:0.0.6
    ports:
      - "80:80"
    env_file:
      - docker.env

  search:
    image: henryspeaker/car-listing-search:0.0.6
    env_file:
      - docker.env
